### PR TITLE
New Logo StatusBarUtil

### PR DESCRIPTION
**Pull request by LuigiBaute**
Hello! here are the [google drive](https://drive.google.com/drive/u/0/my-drive) for any future modifications, enjoy!

### CODE REVIEW

**Comment by LuigiBaute** [comment]
This is the actual [google drive](https://drive.google.com/drive/folders/1n9ZgHMsBz9rkZYa_uMH85DMaTMF9y-RG?usp=sharing) link! enjoy!

**Comment by laobie** [comment]
OK.

**Comment by LuigiBaute** [comment]
@laobie If you ever start another project and need a logo to get better publicity, I can help.

**Comment by laobie** [comment]
OK, Very happy that you are so generous. Thank you.

**Pull request merged**
